UN-OCHA/response-site

.travis.yml
composer.json
git-hooks/pre-commit
git-hooks/scripts/pre-commit/lint-common
git-hooks/scripts/pre-commit/lint-php
git-hooks/scripts/pre-commit/lint-phpcs
git-hooks/scripts/pre-commit/lint-sass
html/modules/custom/hr_paragraphs/hr_paragraphs.module
html/modules/custom/hr_paragraphs/src/Controller/CalFileParser.php
html/modules/custom/hr_paragraphs/src/Controller/ParagraphController.php
html/modules/custom/ocha_docstore_files/src/Plugin/search_api/processor/StoreEntity.php

Also drop in theme asset scripts, we will need them I suspect.

[OPS-7611] Add the git pre-commit hooks and composer script to install them. 

---

.gitignore
html/.gitignore
html/modules/.gitignore
html/profiles/.gitignore
html/sites/.gitignore
html/sites/default/.gitignore
html/themes/.gitignore

I finished setting up my local environment and noticed all these ignore files in my working directory after composer finished. They all seem to be useful so I want to capture, but just in case I am doing something wrong here's a separate PR for them.

chore: add ignore files following composer install

---

html/themes/custom/common_design_subtheme/common_design_subtheme.libraries.yml
html/themes/custom/common_design_subtheme/components/hri-breadcrumbs/hri-breadcrumbs.css

[HRINFO-1128] style breadcrumbs

---

html/modules/custom/hr_paragraphs/hr_paragraphs.links.action.yml
html/modules/custom/hr_paragraphs/hr_paragraphs.links.task.yml
html/modules/custom/hr_paragraphs/hr_paragraphs.module
html/modules/custom/hr_paragraphs/hr_paragraphs.routing.yml
html/modules/custom/hr_paragraphs/src/Controller/ParagraphController.php

Sub tabs for all, reports and infographics
Refs: #HRINFO-1120

Single tab for RW content

---

html/modules/custom/hr_paragraphs/templates/hdx-dataset.html.twig
html/themes/custom/common_design_subtheme/common_design_subtheme.libraries.yml
html/themes/custom/common_design_subtheme/components/hri-table/hri-table.css

[HRINFO-1150] theme the Datasets tab with CD Table component

---

html/modules/custom/hr_paragraphs/src/Controller/ParagraphController.php
html/modules/custom/hr_paragraphs/templates/hdx-dataset.html.twig
html/themes/custom/common_design_subtheme/common_design_subtheme.libraries.yml
html/themes/custom/common_design_subtheme/components/hri-river/hri-river.css
html/themes/custom/common_design_subtheme/templates/layout/rw-river.html.twig

Maps/Infographics tab is now styled. As an MVP I am just looping through the docs and outputting one button per file, as opposed to the dropbutton thing which makes the template waaaay more complicated.

[HRINFO-1158] style the RW River

---

html/modules/custom/hr_paragraphs/hr_paragraphs.module
html/modules/custom/hr_paragraphs/templates/hr-paragraphs-iframe.html.twig

feat(twig): Add template for iframe

---

config/field.field.group.operation.field_paragraphs.yml

Label change for the Paragraphs field.

[HRINFO-1163] better label for Paragraphs field within Operations

---

html/modules/custom/hr_paragraphs/hr_paragraphs.module

feat: mark active tab

---

config/user.role.content_editor.yml
config/user.role.hr_info_admin.yml

feat: Content translation

---

html/modules/custom/hr_paragraphs/hr_paragraphs.module

feat: path alias for subgroups

---

composer.json
composer.lock
config/core.extension.yml
config/user.role.hr_info_admin.yml

feat: Masquerade

---

html/modules/custom/hr_paragraphs/hr_paragraphs.links.task.yml
html/modules/custom/hr_paragraphs/hr_paragraphs.routing.yml
html/modules/custom/hr_paragraphs/src/Controller/ParagraphController.php

feat: Tab for operations

---

html/modules/custom/hr_paragraphs/hr_paragraphs.module

bug: make sure there is an iframe

---

config/field.field.paragraph.child_groups.field_title.yml
config/group.content_type.cluster-group_node-article.yml
config/group.content_type.operation-group_node-article.yml
config/group.content_type.operation-subgroup-cluster.yml
html/modules/custom/hr_paragraphs/hr_paragraphs.module
html/modules/custom/hr_paragraphs/hr_paragraphs.routing.yml

bug: iframe

---

html/modules/custom/hr_paragraphs/src/Controller/ParagraphController.php

feat: RW negate operators

---

config/core.entity_form_display.paragraph.iframe.default.yml
config/core.entity_view_display.paragraph.iframe.default.yml
config/field.field.paragraph.iframe.field_iframe_aspect_ratio.yml
config/field.storage.paragraph.field_iframe_aspect_ratio.yml
html/modules/custom/hr_paragraphs/hr_paragraphs.module
html/themes/custom/common_design_subtheme/common_design_subtheme.libraries.yml
html/themes/custom/common_design_subtheme/components/hri-iframe/hri-iframe.css
html/themes/custom/common_design_subtheme/templates/hr-paragraphs-iframe.html.twig

I realized at the end that most of this should probably live inside the module itself alongside the field definition. At least it isn't coupled to the subtheme.

[HRINFO-1174] allow each iframe to force an aspect ratio

---

html/themes/custom/common_design_subtheme/common_design_subtheme.info.yml
html/themes/custom/common_design_subtheme/common_design_subtheme.libraries.yml
html/themes/custom/common_design_subtheme/components/hri-events/hri-events.css

The content contains lots of `<br>` tags so I hid them.

[HRINFO-1170] tighten up spacing of fullcalendar modal

---

config/block.block.hri_admin_breadcrumbs.yml
config/block.block.hri_admin_content.yml
config/block.block.hri_admin_help.yml
config/block.block.hri_admin_local_actions.yml
config/block.block.hri_admin_local_tasks.yml
config/block.block.hri_admin_messages.yml
config/block.block.hri_admin_page_title.yml
config/block.block.tabs.yml
config/core.entity_form_display.node.page.default.yml
config/core.extension.yml
config/system.theme.yml
html/themes/custom/common_design_subtheme/common_design_subtheme.info.yml
html/themes/custom/hri_admin/css/admin.css
html/themes/custom/hri_admin/hri_admin.info.yml
html/themes/custom/hri_admin/hri_admin.libraries.yml
html/themes/custom/hri_admin/hri_admin.theme

We have a new Seven subtheme for admin tweaks. The UI dialog fix for tall images is included.

[HRINFO-1157] admin subtheme and fix WYSIWYG tall images

---

html/modules/custom/hr_paragraphs/hr_paragraphs.module
html/modules/custom/hr_paragraphs/src/Controller/ParagraphController.php
html/modules/custom/hr_paragraphs/src/Controller/ReliefwebController.php

bug: parse search param for advanced search as well

---

config/core.entity_form_display.paragraph.twitter_feed.default.yml
config/core.entity_view_display.paragraph.twitter_feed.default.yml
config/field.field.paragraph.twitter_feed.field_twitter_account.yml
config/field.storage.paragraph.field_twitter_account.yml
config/paragraphs.paragraphs_type.twitter_feed.yml
html/themes/custom/common_design_subtheme/common_design_subtheme.libraries.yml
html/themes/custom/common_design_subtheme/components/hri-twitter-feed/hri-twitter-feed.css
html/themes/custom/common_design_subtheme/templates/field--paragraph--field-twitter-account--twitter-feed.html.twig

Dedicated paragraph type for Twitter embeds. You enter the account and it does the rest.

[HRINFO-1192] Twitter embeds

---

composer.json
composer.lock
config/core.extension.yml
config/theme_switcher.rule.operation_management.yml

Trying to ease our need to clean up what amount to core output, while avoiding ugly 403s for visitors who try things.

[HRINFO-1210] admin theme for back-room Operation tabs

---

config/editor.editor.basic_html.yml
config/editor.editor.full_html.yml
config/filter.format.basic_html.yml
config/filter.format.full_html.yml

[HRINFO-1208] remove ability to create/render HTML tables in WYSIWYG

---

html/modules/custom/hr_paragraphs/src/Controller/ReliefwebController.php

bug: nested filters with different operators.

---

config/group.type.cluster.yml
config/group.type.operation.yml

bug: Duplicate membership

---

html/modules/custom/hr_paragraphs/src/Controller/ReliefwebController.php

bug: nested and/or query

---

html/modules/custom/hr_paragraphs/hr_paragraphs.module

bug: RW river block parameters

---

html/modules/custom/hr_paragraphs/hr_paragraphs.module
html/modules/custom/hr_paragraphs/src/Controller/ReliefwebController.php

bug: Add extra check for cluster aliases

---

html/modules/custom/hr_paragraphs/src/Controller/ParagraphController.php

[HRINFO-1188] Fix action text for subgroup

---

config/user.role.global_editor.yml
html/modules/custom/hr_paragraphs/hr_paragraphs.links.action.yml
html/modules/custom/hr_paragraphs/hr_paragraphs.module

bug: Allow editor to add operation

---

config/core.entity_form_display.user.user.default.yml
config/core.entity_view_display.user.user.default.yml

Hide the pic and don't allow people to choose or edit them.

[HRINFO-1206] disable user pictures when Users are edited/displayed

---

html/themes/custom/common_design_subtheme/components/hri-global-styling/hri-global-styling.css
html/themes/custom/common_design_subtheme/templates/group--full.html.twig

Applies the salmon color to unpublished nodes.

[HRINFO-1213] apply background-color to all unpublished nodes

---

html/modules/custom/paragraphs_group_permissions/paragraphs_group_permissions.module

bug: Parse url

---

html/themes/custom/common_design_subtheme/common_design_subtheme.libraries.yml
html/themes/custom/common_design_subtheme/js/login_destination.js

feat: Redirect after login

---

config/core.entity_form_display.user.user.default.yml
config/core.entity_view_display.user.user.default.yml

[HRINFO-1206] disable user pictures when Users are edited/displayed. again.

---

config/core.entity_form_display.group.cluster.default.yml
config/core.entity_form_display.group.operation.default.yml
config/field.storage.group.field_enabled_tabs.yml
html/modules/custom/hr_paragraphs/hr_paragraphs.links.task.yml
html/modules/custom/hr_paragraphs/hr_paragraphs.routing.yml
html/themes/custom/common_design_subtheme/templates/hdx-dataset.html.twig

- HRI Layout controls layout
- Same keyboard nav as Rivers with facets
- The label "Datasets" has been changed to "Data"
@attiks this one needs more than a yolo lookover. I felt pretty sure I only touched human-readable instances of `datasets` but please check them to be sure.

[HRINFO-1222] Adjustments to HDX tab

---

config/core.entity_view_display.paragraph.child_groups.default.yml
html/themes/custom/common_design_subtheme/components/hri-bullet-list/hri-bullet-list.css
html/themes/custom/common_design_subtheme/components/hri-layout/hri-layout.css

- removed Text label
- reduced font-size
- adjusted bullet styles

[HRINFO-1225] tighten up the sidebar contents

---

html/themes/custom/common_design_subtheme/components/cd-tabs/hri-tabs.css
html/themes/custom/common_design_subtheme/templates/hr-paragraphs-rw-list.html.twig
html/themes/custom/common_design_subtheme/templates/rw-river.html.twig

Firefox/Lighthouse audits were pretty clean. Some minor fixes.

[HRINFO-1221] a11y review

---

html/themes/custom/common_design_subtheme/templates/cd/cd-header/cd-ocha.html.twig

No more boilerplate in OCHA Services.

[HRINFO-1216] customize the OCHA Services menu

---

html/themes/custom/common_design_subtheme/components/hri-global-styling/hri-global-styling.css

[HRINFO-1225] tighten up the Paragraphs headings

---

html/modules/custom/hr_paragraphs/templates/rw-river.html.twig
html/themes/custom/common_design_subtheme/components/hri-river/hri-river.css
html/themes/custom/common_design_subtheme/templates/rw-river.html.twig

- Show default text when preview is present but body is not.
- Layout bugfix.

[HRINFO-1231] adjust the Rivers

---

html/themes/custom/common_design_subtheme/common_design_subtheme.libraries.yml
html/themes/custom/common_design_subtheme/components/hri-cd-header/hri-cd-header.css

[HRINFO-1234] show RW Ops logo on mobile too

---

config/field.field.group.cluster.field_maps_infographics_link.yml
config/field.field.group.cluster.field_reliefweb_assessments.yml
config/field.field.group.cluster.field_reliefweb_documents.yml
config/field.field.group.operation.field_maps_infographics_link.yml
config/field.field.group.operation.field_reliefweb_assessments.yml
config/field.field.group.operation.field_reliefweb_documents.yml

feat: Labels for RW links

---

html/themes/custom/common_design_subtheme/common_design_subtheme.libraries.yml
html/themes/custom/common_design_subtheme/components/hri-button/hri-button.css
html/themes/custom/common_design_subtheme/components/hri-events/hri-events.css
html/themes/custom/common_design_subtheme/components/hri-events/hri-events.js
html/themes/custom/common_design_subtheme/components/hri-tooltip/hri-tooltip.css
html/themes/custom/common_design_subtheme/templates/hr-paragraphs-rw-list.html.twig
html/themes/custom/common_design_subtheme/templates/river.html.twig
html/themes/custom/common_design_subtheme/templates/upcoming-events.html.twig

- Adds a button to copy event details
- HRI Tooltip component (stolen from GHO)
- Applied some mobile/RTL layout fixes to Upcoming Events
- Applied some RTL fixes to River buttons

[HRINFO-1233] button to copy Upcoming Events details

---

composer.json
composer.lock
html/modules/custom/hr_paragraphs/hr_paragraphs.module
html/modules/custom/hr_paragraphs/src/Controller/RssController.php
html/modules/custom/hr_paragraphs/tests/src/ExistingSite/HrParagraphsRssTest.php
html/modules/custom/hr_paragraphs/tests/src/ExistingSite/Stub/StubRssController.php
phpunit.xml

- theme switcher is disabled during rendering
- node and group rendered in code

test: RSS items

---

html/modules/custom/hr_paragraphs/tests/src/ExistingSite/HrParagraphsRssTest.php

100% coverage of hr_paragraphs_preprocess_paragraph__rss_feed

test: RSS paragraph

---

html/modules/custom/hr_paragraphs/src/Controller/HdxController.php

feat(hdx): Sort facets

---

html/modules/custom/hr_paragraphs/src/Controller/HdxController.php
html/themes/custom/common_design_subtheme/templates/hr-paragraphs-rw-list.html.twig
html/themes/custom/common_design_subtheme/templates/river-row.html.twig
html/themes/custom/common_design_subtheme/templates/river.html.twig

Consolidates the output of Faceted River and River Paragraph output. They both use a common include to output the individual rows of data in the Rivers.

[HRINFO-1231] consolidate River templates to one include

---

html/themes/custom/common_design_subtheme/common_design_subtheme.libraries.yml
html/themes/custom/common_design_subtheme/components/hri-events/hri-events.css
html/themes/custom/common_design_subtheme/components/hri-events/hri-events.js
html/themes/custom/common_design_subtheme/templates/upcoming-events.html.twig

A lot of fighting for such a small diff. Opens each event's description in a jQuery UI Dialog so that it looks pretty much identical to the FullCalendar UI.

[HRINFO-1233] open Upcoming Events details in a modal

---

config/user.role.anonymous.yml
config/user.role.authenticated.yml

Remove Markdown text format from all roles.

[HRINFO-1208] remove Markdown text format from all roles

---

html/themes/custom/common_design_subtheme/templates/upcoming-events.html.twig

In case two paragraphs get added, this ensures unique IDs

[HRINFO-1233] output random HTML IDs on Upcoming Events para

---

config/core.entity_form_display.paragraph.reliefweb_river.default.yml
config/core.entity_form_display.paragraph.upcoming_events.default.yml
config/core.entity_view_display.paragraph.reliefweb_river.default.yml
config/core.entity_view_display.paragraph.reliefweb_river.preview.yml
config/core.entity_view_display.paragraph.upcoming_events.default.yml
config/field.field.paragraph.reliefweb_river.field_max_number_of_items.yml
config/field.field.paragraph.upcoming_events.field_max_number_of_items.yml
html/modules/custom/hr_paragraphs/hr_paragraphs.module

Re-used the existing RSS field to override the default for all Paragraph types.

[HRINFO-1239] Paragraphs should all display 5 items by default

---

config/field.storage.group.field_enabled_tabs.yml

```
drush sqlq "update group_revision__field_enabled_tabs set field_enabled_tabs_value = \"data\" where field_enabled_tabs_value=\"datasets\""
drush sqlq "update group__field_enabled_tabs set field_enabled_tabs_value = \"data\" where field_enabled_tabs_value=\"datasets\""
drush cr
```

HRINFO-1144: Remove old option

---

config/field.field.group.cluster.field_hdx_dataset_link.yml
config/field.field.group.operation.field_hdx_dataset_link.yml

feat: Update HDX description

---

html/modules/custom/hr_paragraphs/src/Controller/ParagraphController.php
html/modules/custom/hr_paragraphs/tests/src/ExistingSite/HrParagraphsHdxTest.php

feat(hdx): At least one filter required.

---

config/views.view.my_groups.yml
html/modules/custom/hr_paragraphs/hr_paragraphs.links.task.yml
html/themes/custom/common_design_subtheme/components/hri-table/hri-table.css
html/themes/custom/common_design_subtheme/templates/views-view-table.html.twig

feat(admin): Better group overview for users

---

config/field.field.node.page.field_paragraphs.yml

feat: Paragraph label

---

config/field.field.paragraph.reliefweb_river.field_max_number_of_items.yml
config/field.field.paragraph.upcoming_events.field_max_number_of_items.yml
html/modules/custom/hr_paragraphs/hr_paragraphs.module

feat: Max items

---

config/filter.format.hr_plain_text.yml
config/filter.format.plain_text.yml
config/user.role.authenticated.yml
config/user.role.global_editor.yml

feat: Plain text

---

html/modules/custom/hr_paragraphs/hr_paragraphs.module
html/modules/custom/hr_paragraphs/tests/src/ExistingSite/HrParagraphsIFrameTest.php

test: iframe

---

html/modules/custom/hr_paragraphs/hr_paragraphs.module

feat: Unblock user when adding as member

---

config/filter.format.basic_html.yml

feat: no tag limit

---

html/modules/custom/hr_paragraphs/hr_paragraphs.module
html/modules/custom/hr_paragraphs/src/Controller/ParagraphController.php

bug: redirect caching

---

html/modules/custom/hr_paragraphs/hr_paragraphs.module

feat: do not add uid 0 and 1 as member

---

html/modules/custom/hr_paragraphs/migrate/common.php

feat: do not fail on 404

---

composer.lock
html/modules/custom/hr_paragraphs/src/Routing/RouteSubscriber.php

feat: Change title

---

html/modules/custom/hr_paragraphs/migrate/README.md
html/modules/custom/hr_paragraphs/src/Commands/HrParagraphsCommands.php

feat: import ops without country

---

html/modules/custom/hr_paragraphs/src/Controller/RssController.php

bug: RSS caching

---

html/modules/custom/hr_paragraphs/hr_paragraphs.module
html/themes/custom/hri_admin/templates/views-view--group-members.html.twig

feat: Link to members of operation

---

composer.lock

chore: update core

---

.github/workflows/composer-update.yml

feat: Drop in the weekly composer auto-patcher.

---

config/system.site.yml
html/modules/custom/hr_paragraphs/tests/src/ExistingSite/HrParagraphsArchiveTest.php
html/modules/custom/hr_paragraphs/tests/src/ExistingSite/HrParagraphsClusterTabTitlesTest.php
html/modules/custom/hr_paragraphs/tests/src/ExistingSite/HrParagraphsClusterTabsTest.php
html/modules/custom/hr_paragraphs/tests/src/ExistingSite/HrParagraphsOperationTabTitlesTest.php
html/modules/custom/hr_paragraphs/tests/src/ExistingSite/HrParagraphsOperationTabsTest.php
html/modules/custom/hr_paragraphs/tests/src/ExistingSite/HrParagraphsPathAliases.php
html/modules/custom/hr_paragraphs/tests/src/ExistingSite/HrParagraphsSidebarTest.php

fix: Use the correct site name.

---

config/field.field.group.cluster.field_paragraphs.yml
config/field.field.group.operation.field_paragraphs.yml
config/field.field.node.page.field_paragraphs.yml
config/paragraphs.paragraphs_type.featured_highlight.yml
config/paragraphs.paragraphs_type.heading.yml
config/paragraphs.paragraphs_type.iframe.yml
config/paragraphs.paragraphs_type.reliefweb_river.yml
config/paragraphs.paragraphs_type.text_block.yml

feat: Rename paragraphs

---

config/theme_switcher.rule.operation_management.yml
html/modules/custom/hr_paragraphs/src/Routing/RouteSubscriber.php

Use the new permission
Refs: #RWR-146

feat: Delete group

---

config/group.role.operation-member.yml
config/views.view.group_members.yml

feat: View members of parent operation

---

config/user.role.global_editor.yml

feat: Multilingual menus

---

config/core.entity_form_display.group.cluster.default.yml
config/core.entity_form_display.group.operation.default.yml
config/core.entity_form_display.node.page.default.yml
config/core.entity_view_display.group.cluster.default.yml
config/core.entity_view_display.group.operation.default.yml
config/core.entity_view_display.paragraph.featured_highlight.default.yml
config/field.field.group.cluster.field_calendar_alternate_link.yml
config/field.field.group.operation.field_calendar_alternate_link.yml
config/field.storage.group.field_calendar_alternate_link.yml
config/paragraphs.paragraphs_type.layout.yml
html/modules/custom/hr_paragraphs/hr_paragraphs.module
html/modules/custom/hr_paragraphs/src/Controller/ParagraphController.php

feat: Alternate source for events

---

html/modules/custom/hr_paragraphs/drush.services.yml
html/modules/custom/hr_paragraphs/src/Commands/HrParagraphsCommands.php

bug: image migration

---

html/modules/custom/hr_paragraphs/src/Controller/HdxController.php
html/modules/custom/hr_paragraphs/src/Controller/ParagraphController.php

feat: Expose feature filter for HDX

---

html/modules/custom/hr_paragraphs/src/Controller/CalFileParser.php
html/modules/custom/hr_paragraphs/src/Controller/IcalController.php

bug: ical feed without timezone

---

html/modules/custom/hr_paragraphs/src/Controller/HdxController.php

feat: Combine featured HDX filters

---

html/themes/custom/common_design_subtheme/components/hri-card-list/hri-card-list.css
html/themes/custom/hri_admin/css/admin.css

fix: Card List should create fixed-width Cards

---

html/modules/custom/hr_paragraphs/hr_paragraphs.module

feat: Remove layout paragraph

---

html/themes/custom/common_design_subtheme/templates/paragraph--card-list--featured-highlight.html.twig
html/themes/custom/common_design_subtheme/templates/paragraph--landing-page--heading.html.twig

Our hardcoded silliness is already showing its head.

[RWR-155] fix the href for Headings inside Landing Pages

---

README.md
html/modules/custom/hr_paragraphs/hr_paragraphs.install
html/modules/custom/hr_paragraphs/migrate/README.md
html/modules/custom/hr_paragraphs/src/Commands/HrParagraphsCommands.php

feat: Drush command to import users

---

html/modules/custom/hr_paragraphs/src/Commands/HrParagraphsCommands.php

bug: Make sure mandatory fields are not empty

---

html/modules/custom/hr_paragraphs/hr_paragraphs.module
html/modules/custom/hr_paragraphs/hr_paragraphs.services.yml
html/modules/custom/hr_paragraphs/src/EventSubscriber/SocialAuthSubscriber.php

feat: Notify team, username is email

---

html/themes/custom/common_design_subtheme/templates/views-view--locations--page-locations.html.twig
html/themes/custom/common_design_subtheme/templates/views-view-grid.html.twig

Emma tested dev and found some 🐞 crawling around.

[RWR-156] Small fixes for Locations page

---

config/views.view.locations.yml

Minor config updates for Locations page.

[RWR-156] Correct title for Locations page

---

composer.lock

security: update core

---

config/views.view.locations.yml

We want to display archive status on the Locations page.

[RWR-156] display Archive status on Location list

---

config/views.view.locations.yml

fix: archive text needs leading whitespace

---

config/csp.settings.yml

Refs: OPS-8232
More picked up from the logs - already changed in the UI, this to keep
the code up-to-date.

fix: more csp config

---

html/modules/custom/hr_paragraphs/src/Controller/GroupContentTitleController.php
html/modules/custom/hr_paragraphs/src/Routing/RouteSubscriber.php

feat: Title for group content

---

html/themes/custom/common_design_subtheme/components/hri-global-styling/hri-global-styling.css
html/themes/custom/common_design_subtheme/components/hri-river/hri-river.css

[RWR-192] match RW colors more closely

---

html/modules/custom/hr_paragraphs/src/Controller/HdxController.php

bug: fix multivalue HDX filter

---

html/modules/custom/hr_paragraphs/templates/hr-paragraphs-rw-list.html.twig
html/modules/custom/hr_paragraphs/templates/river.html.twig
html/themes/custom/common_design_subtheme/templates/field--paragraph--field-twitter-account--twitter-feed.html.twig
html/themes/custom/common_design_subtheme/templates/hr-paragraphs-rw-list.html.twig
html/themes/custom/common_design_subtheme/templates/river-row.html.twig
html/themes/custom/common_design_subtheme/templates/river.html.twig
html/themes/custom/common_design_subtheme/templates/views-view--locations--page-locations.html.twig

feat: Translate twig strings

---

config/views.view.group_nodes.yml

bug: duplicate rows

---

composer.json
composer.lock

chore: periodic updates

---

config/core.entity_form_display.paragraph.iframe.default.yml
html/modules/custom/hr_paragraphs/hr_paragraphs.install
html/modules/custom/hr_paragraphs/hr_paragraphs.module
html/modules/custom/hr_paragraphs/src/LongLinkItem.php
html/modules/custom/hr_paragraphs/src/Plugin/Field/FieldWidget/HrParagraphsLongLinkWidget.php

feat: Allow links up to 4096 characters

---

config/group.role.cluster-manager.yml
config/group.role.operation-manager.yml

feat: Access unpublished groups

---

config/field.field.group.cluster.field_paragraphs.yml
config/field.field.group.operation.field_paragraphs.yml
config/field.field.node.landing_page.field_paragraphs.yml
config/field.field.node.landing_page.field_paragraphs_secondary.yml
config/field.field.node.page.field_paragraphs.yml
config/paragraphs.paragraphs_type.table_of_contents.yml
html/themes/custom/common_design_subtheme/components/hri-toc/hri-toc.js

Modifies the ToC Paragraph type to allow placement anywhere.

[RWR-185] Allow placement of ToC everywhere

---

config/views.view.audit_paragraphs.yml

New admin-only page to see what content uses custom CSS.
Refs: RWR-191

[RWR-191] add a new Audit to see what content uses custom CSS

---

composer.lock

chore: update all drupal modules and dependencies

---

config/views.view.group_nodes.yml
config/views.view.groups.yml
html/modules/custom/hr_paragraphs/hr_paragraphs.module

feat: Exposed filters on groups

---

config/field.storage.paragraph.field_iframe_url.yml
html/modules/custom/hr_paragraphs/hr_paragraphs.module
html/modules/custom/hr_paragraphs/src/Controller/KeyFiguresController.php

Rwr 196 cache

---

config/editor.editor.full_html.yml
config/image.style.migrate_max_size.yml
html/modules/custom/hr_paragraphs/src/Commands/HrParagraphsCommands.php

Make sure images are max 2000*2000

---

config/views.view.content.yml
html/modules/custom/hr_paragraphs/hr_paragraphs.module

feat: Filter by group on admin/content

---

config/core.entity_form_display.node.page.default.yml
config/core.entity_view_display.node.page.default.yml
config/core.entity_view_display.node.page.full.yml
config/core.entity_view_display.node.page.operation_tab.yml
config/core.entity_view_display.node.page.rss.yml
config/core.entity_view_display.node.page.teaser.yml
config/field.field.node.page.field_hide_sidebar.yml
config/field.storage.node.field_hide_sidebar.yml
html/modules/custom/hr_paragraphs/hr_paragraphs.module

feat: Hide sidebar on pages

---

config/core.entity_form_display.group.cluster.default.yml
config/core.entity_form_display.group.operation.default.yml
html/modules/custom/hr_paragraphs/hr_paragraphs.module
html/themes/custom/hri_admin/css/admin.css

feat: Make empty paragraphs visible for editors

---

html/modules/custom/hr_paragraphs/hr_paragraphs.module

feat: Exposed filter on clusters

---

html/modules/custom/hr_paragraphs/src/Controller/IcalController.php
html/themes/custom/common_design_subtheme/templates/upcoming-events.html.twig

feat: Use local time for upcoming events

---

html/modules/custom/hr_paragraphs/hr_paragraphs.module
html/modules/custom/hr_paragraphs/src/Controller/ParagraphController.php
html/modules/custom/hr_paragraphs/tests/src/ExistingSite/HrParagraphsHdxTest.php
html/themes/custom/common_design_subtheme/templates/river.html.twig

feat: No facets, link to source

---

html/modules/custom/hr_paragraphs/src/Controller/ParagraphController.php

bug: fix cache tag

---

html/themes/custom/common_design_subtheme/templates/views-view--locations--page-locations.html.twig

[RWR-217] avoid duplicating top-level classes on Locations letter nav

---

config/views.view.locations.yml

[RWR-156] force the space when displaying a Location as archived

---

html/modules/custom/hr_analytics/hr_analytics.module

feat: GTM datalayer

---

html/themes/custom/common_design_subtheme/components/hri-calendar/hri-calendar.css

feat: Styling calendar popup

---

composer.json
composer.lock
config/core.extension.yml
html/modules/custom/hr_mailchimp/README.md
html/modules/custom/hr_mailchimp/composer.json
html/modules/custom/hr_mailchimp/hr_mailchimp.info.yml
html/modules/custom/hr_mailchimp/hr_mailchimp.module
html/themes/custom/common_design_subtheme/components/hri-calendar/hri-calendar.css

feat: Subscribe to mailchimp

---

html/modules/custom/hr_paragraphs/hr_paragraphs.module
html/themes/custom/common_design_subtheme/components/node-edit-link/node-edit-link.css

bug: missing css for edit link

---

html/themes/custom/common_design_subtheme/components/cd-tabs/hri-tabs.css
html/themes/custom/common_design_subtheme/components/google-cse/google-cse.css
html/themes/custom/common_design_subtheme/components/hri-button/hri-button.css
html/themes/custom/common_design_subtheme/components/hri-events/hri-events.css
html/themes/custom/common_design_subtheme/components/hri-pagination/hri-pagination.css
html/themes/custom/common_design_subtheme/css/brand.css
html/themes/custom/common_design_subtheme/css/styles.css

Ultimately the red was too crass for the group. A wholesale revert would have undone other necessary work like base-theme upgrade, and a reorg of a couple stylesheets that needed to happen.

[RWR-174] revert color changes

---

html/modules/custom/hr_mailchimp/hr_mailchimp.module

feat: Add logging for mailchimp

---

config/field.storage.paragraph.field_country.yml

[RWR-220] add Pakistan to Key Figures config

---

html/modules/custom/hr_paragraphs/component/events/js/fullcalendar.js
html/modules/custom/hr_paragraphs/src/Controller/ParagraphController.php

feat: Add ical button to calendar

---

html/modules/custom/hr_paragraphs/hr_paragraphs.module

feat: Use pages as tab name

---

CHANGELOG.md
composer.json

chore(release): v0.3.0

---

html/modules/custom/hr_paragraphs/templates/hr-paragraphs-rw-list.html.twig
html/modules/custom/hr_paragraphs/templates/river.html.twig
html/themes/custom/common_design_subtheme/templates/river-row.html.twig

[RWR-236] change label on Rivers and RW docs

---

config/csp.settings.yml

chore: add more exceptions for csp

---

config/core.entity_form_display.group.operation.default.yml
html/themes/custom/hri_admin/css/admin.css

[RWR-237] move Custom Content help text to be under title

---

html/modules/custom/hr_paragraphs/hr_paragraphs.module
html/modules/custom/hr_paragraphs/src/Controller/KeyFiguresController.php
html/modules/custom/hr_paragraphs/src/Controller/ParagraphController.php

feat: Handle exceptions

---

config/hr_paragraphs.settings.yml
html/modules/custom/hr_paragraphs/config/install/hr_paragraphs.settings.yml
html/modules/custom/hr_paragraphs/config/schema/hr_paragraphs.schema.yml
html/modules/custom/hr_paragraphs/src/EventSubscriber/SocialAuthSubscriber.php

feat: Add flag to disable notification for new users

---

html/modules/custom/hr_paragraphs/hr_paragraphs.module
html/modules/custom/hr_paragraphs/hr_paragraphs.services.yml
html/modules/custom/hr_paragraphs/src/Config/LanguageConfigOverrides.php

feat: Translate views tab names

---

html/themes/custom/common_design_subtheme/components/hri-heading/hri-heading.css
html/themes/custom/common_design_subtheme/templates/paragraph--landing-page--heading.html.twig

It's more similar to RW, plus more bidi-friendly now.

[RWR-245] change link next to the homepage heading

---

html/modules/custom/hr_paragraphs/templates/hr-paragraphs-rw-list.html.twig
html/modules/custom/hr_paragraphs/templates/river.html.twig
html/modules/custom/hr_paragraphs/templates/upcoming-events.html.twig
html/themes/custom/common_design_subtheme/templates/river-row.html.twig
html/themes/custom/common_design_subtheme/templates/upcoming-events.html.twig

[RWR-236] format dates like RW

---

html/themes/custom/common_design_subtheme/components/hri-rss-feed/hri-rss-feed.css
html/themes/custom/common_design_subtheme/components/hri-text-block/hri-text-block.css

[RWR-249] revert color to currentColor

---

composer.json
composer.lock
config/core.extension.yml
config/language/es/views.view.paragraphs.yml
config/language/fr/views.view.paragraphs.yml
config/views.view.paragraphs.yml

feat: Add paragraph overview

---

CHANGELOG.md
composer.json

chore(release): 0.4.0

---

config/core.entity_form_display.paragraph.card_list.default.yml
config/core.entity_view_display.paragraph.card_list.default.yml
config/field.field.paragraph.card_list.field_numcols.yml
config/field.storage.paragraph.field_numcols.yml
html/themes/custom/common_design_subtheme/components/hri-card-list/hri-card-list.css
html/themes/custom/common_design_subtheme/templates/field--paragraph--card-list.html.twig
html/themes/custom/common_design_subtheme/templates/paragraph--card-list.html.twig
html/themes/custom/hri_admin/css/admin.css
html/themes/custom/hri_admin/templates/paragraph--card-list--preview.html.twig

Now there's a dropdown to make it 3-column.

[RWR-247] add 3-col option to Card List

---

html/themes/custom/hri_admin/css/admin.css

fix: restrict Description styles to node/group entities

---

html/modules/custom/hr_paragraphs/src/Controller/RssController.php
html/modules/custom/paragraphs_group_permissions/paragraphs_group_permissions.module

feat: Check node access as well on create

---

config/views.view.locations.yml

fix: remove lang filter and print translations individually

---

html/themes/custom/common_design_subtheme/templates/views-view--locations--page-locations.html.twig

fix: add hidden title, match RW markup better

---

html/modules/custom/hr_paragraphs/src/Commands/HrParagraphsCommands.php

feat: Empty sidebar on migration

---

html/themes/custom/common_design_subtheme/components/hri-toc/hri-toc.js

bug: Do not remove content

---

html/themes/custom/common_design_subtheme/templates/hr-paragraphs-rss-feed.html.twig
html/themes/custom/common_design_subtheme/templates/river-row.html.twig

chore: set target to blank where hri__external-url span exists
Refs: RWR-174

RWR-174 Open external links in new browser tab

---

composer.json
composer.lock
config/core.extension.yml
config/views.view.group_members.yml

feat: Export group members

---

html/modules/custom/hr_paragraphs/hr_paragraphs.module

feat: Auto update RW url

---

html/modules/custom/paragraphs_group_permissions/paragraphs_group_permissions.module

bug: Permissions on nested paragraphs

---

html/modules/custom/paragraphs_group_permissions/paragraphs_group_permissions.module

bug: Make sure parent is set

---

html/modules/custom/hr_paragraphs/src/Controller/HdxController.php

feat: New cod filter format

---

html/modules/custom/hr_paragraphs/src/Commands/HrParagraphsCommands.php

bug: Force English as language

---

config/views.view.backlinks_in_paragraphs.yml

feat: Display content linking back to hrinfo

---

html/modules/custom/hr_paragraphs/hr_paragraphs.module

bug: Only change URL is paragraph already exists

---

html/modules/custom/hr_paragraphs/src/Commands/HrParagraphsCommands.php

feat: Generate report for backlinks

---

html/modules/custom/hr_paragraphs/src/Commands/HrParagraphsCommands.php

chore: Better labels for report for backlinks

---

config/views.view.locations.yml

fix: force whitespace before languages in Locations list

---

html/themes/custom/common_design_subtheme/css/styles.css

fix: remove border from titles that live inside a paragraph

---

config/environment_indicator.switcher.demo.yml
config/environment_indicator.switcher.dev.yml

bug: no trailing slash

---

composer.json
composer.lock
config/block.block.ochasearch.yml
config/core.extension.yml
config/ocha_search.settings.yml
html/modules/custom/hr_paragraphs/src/Controller/HdxController.php
html/themes/custom/common_design_subtheme/templates/block--ocha-search-block.html.twig
html/themes/custom/common_design_subtheme/templates/cd/cd-header/cd-site-header.html.twig

feat: OCHA search

---

config/dashboards.dashboard.global_editors.yml
config/views.view.db_group_managers.yml
config/views.view.db_new_groups.yml
html/modules/custom/hr_paragraphs/hr_paragraphs.install
html/modules/custom/hr_paragraphs/hr_paragraphs.module

Refs: #RWR-292, #RWR-300, #RWR-301

feat: Dashboard - new groups, managers

---

config/dashboards.dashboard.global_editors.yml
config/linkchecker.settings.yml
config/views.view.db_links.yml
config/views.view.db_new_groups.yml
config/views.view.db_translated_clusters.yml
config/views.view.db_translated_operations.yml

feat: Dashboard - backlinks

---

.gitattributes
PATCHES/linkchecker_null_link.patch
PATCHES/linkchecker_use_uid.patch
composer.json
composer.lock
composer.patches.json
config/dashboards.dashboard.groups.yml
config/dashboards.dashboard.links.yml
config/dashboards.dashboard.pages.yml
config/linkchecker.settings.yml
config/user.role.global_editor.yml
config/views.view.db_clusters.yml
config/views.view.db_enabled_tabs.yml
config/views.view.db_group_managers.yml
config/views.view.db_groups_never_updated.yml
config/views.view.db_last_editor.yml
config/views.view.db_links.yml
config/views.view.db_new_groups.yml
config/views.view.db_operations.yml
config/views.view.db_translated_clusters.yml
config/views.view.db_translated_operations.yml
config/views.view.db_translated_pages.yml
config/views.view.db_used_paragraphs.yml
config/views.view.db_used_paragraphs_on_pages.yml
config/views.view.groups.yml

- Use Guzzle 7
- Auto fix redirects
- Allow uid instead of name
Refs: #RWR-292

feat: Dashboard

---

config/core.extension.yml
config/views.view.db_clusters.yml
config/views.view.db_operations.yml
html/modules/custom/hr_entity_freshness/hr_entity_freshness.info.yml
html/modules/custom/hr_entity_freshness/hr_entity_freshness.install
html/modules/custom/hr_entity_freshness/hr_entity_freshness.module
html/modules/custom/hr_entity_freshness/src/HrEntityFreshnessInfo.php
html/modules/custom/hr_entity_freshness/src/Plugin/views/field/HrEntityFreshnessTimestamp.php
html/modules/custom/hr_paragraphs/hr_paragraphs.module
html/modules/custom/hr_paragraphs/src/Controller/ParagraphController.php

feat: Track freshness

---

html/themes/custom/common_design_subtheme/components/node-edit-link/node-edit-link.css
html/themes/custom/common_design_subtheme/package-lock.json
html/themes/custom/common_design_subtheme/package.json

One minute updating CSS, two hours debugging dependencies 🙃

[RWR-308] z-index issue

---

html/modules/custom/hr_paragraphs/src/Controller/CalFileParser.php
html/modules/custom/hr_paragraphs/src/Controller/IcalController.php
html/themes/custom/common_design_subtheme/templates/upcoming-events.html.twig

feat: Use timezone string if present

---

config/redirect.settings.yml
docker/Dockerfile
docker/etc/nginx/apps/drupal/fastcgi_drupal.conf

bug: fix redirect

---

html/themes/custom/common_design_subtheme/templates/node--full.html.twig

fix: pages now have compact sidebars

---

config/dashboards.dashboard.groups.yml
config/views.view.db_hdx_cod.yml

feat: List hdx ext_cod links

---

html/modules/custom/hr_paragraphs/hr_paragraphs.module

feat: Allow upcoming events on pages

---

html/themes/custom/common_design_subtheme/templates/upcoming-events.html.twig

feat: Remove timezone

---

html/modules/custom/hr_paragraphs/hr_paragraphs.module
html/modules/custom/hr_paragraphs/hr_paragraphs.post_update.php

feat: Rename Cameroun

---

config/dashboards.dashboard.groups.yml
config/dashboards.dashboard.pages.yml
config/views.view.db_h1_on_pages.yml
config/views.view.db_h1_used.yml

feat: List use of H1

---

html/modules/custom/hr_paragraphs/hr_paragraphs.module

feat: Remove H1 in editor

---

html/modules/custom/hr_paragraphs/src/Controller/IcalController.php

bug: DTEND not set

---

.github/workflows/run-tests.yml
config/filter.format.basic_html.yml

bug: Fix invalid tags

---

composer.lock

Refs: CD-448
Brings in the change from https://github.com/UN-OCHA/ocha_search/pull/6

chore: update ocha_search module

---

.dockerignore
docker/Dockerfile

chore: add dockerignore and update dockerfile

---

html/modules/custom/hr_paragraphs/src/Controller/RssController.php

feat: Support atom feeds

---

config_dev/stage_file_proxy.settings.yml
html/themes/custom/common_design_subtheme/components/hri-homepage/hri-homepage.css

Refs: RWR-325
New origin for `stage_file_proxy` also included - following up on #524

[RWR-325] homepage nudges

---

html/themes/custom/common_design_subtheme/js/login_destination.js

feat: login destination

---

html/modules/custom/hr_paragraphs/hr_paragraphs.module

feat: Hide language from managers

---

config/views.view.db_clusters.yml
config/views.view.db_enabled_tabs.yml
config/views.view.db_groups_never_updated.yml
config/views.view.db_h1_used.yml
config/views.view.db_hdx_cod.yml
config/views.view.db_last_editor.yml
config/views.view.db_links.yml
config/views.view.db_new_groups.yml
config/views.view.db_operations.yml
config/views.view.db_translated_clusters.yml
config/views.view.db_translated_operations.yml
config/views.view.db_used_paragraphs.yml
html/modules/custom/hr_paragraphs/hr_paragraphs.module
html/modules/custom/hr_paragraphs/templates/hr-paragraphs-iframe-powerbi.html.twig
html/themes/custom/common_design_subtheme/templates/hr-paragraphs-iframe-powerbi.html.twig

feat: Allow popup for powerbi

---

html/modules/custom/hr_paragraphs/hr_paragraphs.post_update.php

chore: Fix Afghanistan aliases

---

composer.json
composer.lock

fix: upgrade to CD v8.0.1 and crush the img bug

---

config/language.config.es.user.mail.yml
config/language.config.fr.user.mail.yml
config/user.mail.yml

chore: Override email templates in multiple languages.

---

html/modules/custom/hr_paragraphs/src/Plugin/EntityReferenceSelection/AllUsersSelection.php

feat: Select user by email

---

PATCHES/hid_lang.patch
composer.patches.json

Refs: #RWR-330
As a patch to test, if it's working will update the module

feat: Keep lang code in redirect

---

composer.patches.json

revert: Keep lang code in redirect

---

html/modules/custom/hr_paragraphs/src/Controller/HdxController.php
html/modules/custom/hr_paragraphs/tests/src/ExistingSite/HrParagraphsHdxTest.php

chore: avoid errors when HDX api is down

---

config/views.view.db_links.yml
html/modules/custom/hr_paragraphs/README.md
html/modules/custom/hr_paragraphs/drush.services.yml
html/modules/custom/hr_paragraphs/src/Commands/HrParagraphsBacklinksCommands.php

feat: Fix backlinks

---

html/modules/custom/hr_paragraphs/src/Controller/RssController.php
html/modules/custom/hr_paragraphs/tests/src/ExistingSite/HrParagraphsRssAtomTest.php
html/modules/custom/hr_paragraphs/tests/src/ExistingSite/HrParagraphsRssIllegalTest.php
html/modules/custom/hr_paragraphs/tests/src/Traits/RssAtomTestDataTrait.php
html/modules/custom/hr_paragraphs/tests/src/Traits/RssIllegalTestDataTrait.php

- test: Atom feed
- test: Atom feed

test atom feed

---

html/modules/custom/hr_paragraphs/src/Controller/ReliefwebController.php

fix: allow for missing formats

---

html/modules/custom/hr_paragraphs/hr_paragraphs.module
html/themes/custom/common_design_subtheme/components/hri-iframe/hri-iframe.js

[RWR-275] PowerBI/Tableau need height prop in theme definitions

---

config/core.base_field_override.paragraph.table_of_contents.created.yml
config/core.base_field_override.paragraph.table_of_contents.status.yml
config/core.menu.static_menu_link_overrides.yml
config/field.field.paragraph.table_of_contents.field_text.yml
config/field.field.paragraph.table_of_contents.field_title.yml
config/language.content_settings.paragraph.table_of_contents.yml

Check the checkbox. I also moved around the masquerade links because having multiple top-level items in User menu isn't expected by CD.

[RWR-356] Translatable ToC

---

config/language.content_settings.paragraph.call_to_action.yml

fix: allow Subscribe buttons to be translated

---

html/themes/custom/common_design_subtheme/js/login_destination.js
html/themes/custom/common_design_subtheme/package-lock.json

chore: run npm audit fix to change source for word-wrap package

---

.gitignore
local/.env.example
local/README.md
local/docker-compose.yml
local/exec.sh
local/install.sh
local/shared/settings/services.yml
local/shared/settings/settings.local.php
local/shared/settings/settings.memcache.php
local/shared/settings/settings.site.php

chore: add standard local setup

---

html/themes/custom/common_design_subtheme/components/hri-dropbutton/hri-dropbutton.css

bug: Dropdown inside table

---

html/modules/custom/hr_paragraphs/css/admin.css

bug: Add missing admin css

---

config/group.role.cluster-anonymous.yml
config/group.role.cluster-manager.yml
config/group.role.cluster-member.yml
config/group.role.cluster-outsider.yml
config/group.role.operation-anonymous.yml
config/group.role.operation-manager.yml
config/group.role.operation-member.yml
config/group.role.operation-outsider.yml

bug: view revisions

---

html/modules/custom/hr_paragraphs/css/admin.css

Some other Editor styles thrown in for funsies.

[RWR-378] RSS feed text size for Editors

---

html/modules/custom/hr_paragraphs/hr_paragraphs.module

bug: Duplicate revisions tab

---

.github/workflows/composer-update.yml

In favour of https://github.com/UN-OCHA/response-site/pull/641
Refs: OPS-9656

chore: Allow manual run against a chosen branch.

---

.docksal/docksal.env
docker/Dockerfile
html/modules/custom/hr_paragraphs/src/Access/CustomAccessGroupType.php

chore: Drupal 10 sites run on PHP 8.2.

---

html/modules/custom/hr_paragraphs/css/admin.css

bug: long links break layout

---

config/editor.editor.full_html.yml
config/google_tag.container.default.yml
config/views.view.broken_links_report.yml
config/views.view.content.yml
config/views.view.db_clusters.yml
config/views.view.db_enabled_tabs.yml
config/views.view.db_groups_never_updated.yml
config/views.view.db_last_editor.yml
config/views.view.db_new_groups.yml
config/views.view.db_operations.yml
config/views.view.db_translated_clusters.yml
config/views.view.db_translated_operations.yml
config/views.view.db_translated_pages.yml
config/views.view.db_used_paragraphs.yml
config/views.view.db_used_paragraphs_on_pages.yml
config/views.view.files.yml
config/views.view.glossary.yml
config/views.view.group_members.yml
config/views.view.group_nodes.yml
config/views.view.groups.yml
config/views.view.my_groups.yml
config/views.view.subgroups_of_a_group.yml
html/modules/custom/hr_paragraphs/src/Controller/ParagraphController.php

Yesterday I mentioned repeated need to import config, which after successful import still says it needs to be imported. I tried the reverse and this is the export I got. Do we need this in the codebase or would it be reverting changes?
Once I ran this export, my drush commands started working as expected, saying the config matches the DB.
My DB was Production, 3 Oct 2023 15:18
@attiks halp me understand what I've done! 😱

chore: export config that repeatedly says needs importing

---

html/modules/custom/hr_paragraphs/src/Plugin/views/field/LinkcheckerLinkPageEntityLink.php

bug: Nested paragraphs

---

config/views.view.group_nodes.yml
config/views.view.subgroups_of_a_group.yml

feat: Do not show translations

---

tests/vrt/urls_anon.txt

chore: URLs to test

---

config/core.extension.yml
config/language/es/metatag.metatag_defaults.front.yml
config/language/es/metatag.metatag_defaults.global.yml
config/language/es/metatag.metatag_defaults.node.yml
config/language/es/metatag.metatag_defaults.taxonomy_term.yml
config/language/es/metatag.metatag_defaults.user.yml
config/language/fr/metatag.metatag_defaults.front.yml
config/language/fr/metatag.metatag_defaults.node.yml
config/language/fr/metatag.metatag_defaults.taxonomy_term.yml
config/language/fr/metatag.metatag_defaults.user.yml
config/metatag.metatag_defaults.group.yml
config/metatag.metatag_defaults.group__cluster.yml
config/metatag.metatag_defaults.group__operation.yml
config/views.settings.yml
config/views.view.locations.yml
html/modules/custom/hr_paragraphs/hr_paragraphs.module

feat: Fixes for metatags

---

html/modules/custom/hr_paragraphs/hr_paragraphs.module

feat: Add cluster member/manager to operation

---

composer.json
composer.lock

chore: remove uninstalled contrib ckeditor

---

composer.json
composer.lock

Refs: updates
Like https://github.com/UN-OCHA/iasc8/pull/871, this got tangled in D10 support. Moving to 4.x fixes things.

chore: update csv_serialization module

---

docker/Dockerfile

chore: keep composer version as set in php image

---

composer.lock

Refs: OPS-9867 - security update for group module

Deploy 13-12-2023

---

html/modules/custom/hr_paragraphs/hr_paragraphs.install

feat: Remove global editors from all groups

---

config/user.role.global_editor.yml
html/modules/custom/hr_paragraphs/hr_paragraphs.module
html/modules/custom/hr_paragraphs/hr_paragraphs.permissions.yml

feat: Add permission to unpublish groups

---

html/modules/custom/hr_paragraphs/hr_paragraphs.module

chore: Add cache context/tags

---

html/modules/custom/hr_paragraphs/hr_paragraphs.module

@attiks, fyi that this will be included in the deployment tomorrow.

Deploy 21/02/24

---

config/linkchecker.settings.yml

feat: Ignore code 307

---

composer.json
composer.lock
composer.patches.json

Refs: OPS-10210
Bonus updates - drush and unocha/* packages will soon be included in the automatic updates.

chore: update other packages

---

Makefile
local/docker-compose.yml
local/shared/settings/settings.local.php
tests/docker-compose.yml

chore: update local setup

---

html/modules/custom/hr_paragraphs/src/Controller/IcalController.php

bug: excluded dates should not use time

---

config/views.view.db_h1_on_pages.yml
config/views.view.db_translated_pages.yml
config/views.view.db_used_paragraphs_on_pages.yml
config/views.view.groups.yml

bug: Permissions on admin/group

---

config/field.field.paragraph.featured_highlight.field_image.yml

bug: Mark file as being translatable as well

---

config/seckit.settings.yml

Hotfixed on production, this is to make it stick.
Refs: RWR-439

chore: Add new URLs to seckit frame-src

---

config/seckit.settings.yml

chore: another domain for csp config

---

config/seckit.settings.yml

Refs: RWR-445
Added already via the UI.

chore: add facebook and twitter domains for csp

---

composer.lock

chore: Update ocha monitoring

---

PATCHES/linkchecker-fallback-get-3334240.diff
composer.patches.json
config/linkchecker.settings.yml
config/views.view.db_links.yml

feat: Hide old revisions

---

html/modules/custom/hr_paragraphs/hr_paragraphs.module

feat: Auto update child paths

---

config/xmlsitemap.xmlsitemap.2e9ZfIfLFCC0V-PbcDKUTb1Wk22XgjzJ6f-b16CFlPE.yml
config/xmlsitemap.xmlsitemap.t9UQ7FvqR0wMQMnd5n2XukH0kM9liAM9wOhfSLRl2qw.yml

feat: Sitemaps per ;anguage

---

CHANGELOG.md
composer.json
composer.lock

chore: Add tools

---

config/hr_paragraphs.settings.yml
html/modules/custom/hr_paragraphs/config/install/hr_paragraphs.settings.yml
html/modules/custom/hr_paragraphs/config/schema/hr_paragraphs.schema.yml
html/modules/custom/hr_paragraphs/src/Controller/ReliefwebController.php

feat: Allow the RW API endpoint URL to be set (via Ansible) by using dependency injection.

---

composer.lock

chore: bump version of cd

---

html/themes/custom/common_design_subtheme/templates/node--page--full--pdf.html.twig

style: wrap links for pdf

---

CHANGELOG.md
composer.json
composer.lock

Add style change to tomorrow's deployment.
Untangle version number generated in deploy script.

Deploy 20-11-2024

---

config/seckit.settings.yml

chore: add mailchimp to csp config

---

html/modules/custom/hr_paragraphs/src/Controller/ReliefwebController.php

fix: add gzip header to avoid errors

---

html/themes/custom/common_design_subtheme/components/sitrep/sitrep.css

feat: Do not display links in print version

---

html/modules/custom/rwr_sitrep/rwr_sitrep.module
html/themes/custom/common_design_subtheme/components/sitrep/sitrep.css

Deploy 18-12-2024 - pt 2

---

PATCHES/group_revision_tab-3397063.patch
composer.patches.json

fix: add patch to show group revision tab

---

composer.lock
composer.patches.json
html/modules/custom/hr_paragraphs/src/Plugin/views/field/LinkcheckerLinkPageEntityLink.php

updates: weekly updates

---

composer.json
composer.lock

chore: remove unused admin theme

---

config/filter.format.basic_html.yml

Refs: RWR-497
This change has already happened on prod.

fix: revert text format change for unintended side-effect

---

composer.lock
config/filter.format.basic_html.yml

Changes from https://github.com/un-ocha/response-site/releases/tag/v1.4.4 but including https://github.com/UN-OCHA/response-site/pull/895

Deploy 21-02-2024 

---

docker/settings.php

fix: Use include and not include_once because software sucks.

---

html/themes/custom/common_design_subtheme/templates/node--page--full--pdf.html.twig

fix: include sidebar on sitrep pages

---

PATCHES/social_auth-type-error-3496656.patch
composer.patches.json

fix: include patch for social_auth bug

---

PATCHES/social_auth-type-error-3496656.patch
composer.lock
composer.patches.json

Include patch with changes already prepared: https://github.com/UN-OCHA/response-site/pull/914

Deploy 20-03-2025

---

PATCHES/link_allowed_hosts-return-types.patch
composer.patches.json

updates: patch for return types error

---

PATCHES/linkchecker--check-parent.patch
composer.json
composer.lock
composer.patches.json
config/views.view.db_links.yml
html/modules/custom/fullcalendar_api/fullcalendar_api.libraries.yml
html/modules/custom/fullcalendar_api/fullcalendar_api.module
html/modules/custom/fullcalendar_api/js/fullcalendar.load.js
html/modules/custom/hr_paragraphs/component/events/js/fullcalendar.js
html/modules/custom/hr_paragraphs/hr_paragraphs.libraries.yml
html/modules/custom/hr_paragraphs/src/Controller/ParagraphController.php
html/modules/custom/hr_paragraphs/src/Controller/ReliefwebController.php
html/modules/custom/hr_paragraphs/src/Plugin/views/filter/LinkcheckerLinkActiveRevisions.php
html/themes/custom/common_design_subtheme/components/hri-calendar/hri-calendar.css

bug: update patch for linkchecker

---

composer.json
composer.lock
config/core.extension.yml
config/honeypot.settings.yml
config/key.key.entraid_client_secret.yml
config/monitoring.sensor_config.core_requirements_openid_connect.yml
config/ocha_entraid.settings.yml
config/openid_connect.client.unite_id.yml
config/openid_connect.settings.yml
config/social_auth_hid.settings.yml
config/user.role.anonymous.yml
html/themes/custom/common_design_subtheme/common_design_subtheme.libraries.yml
html/themes/custom/common_design_subtheme/components/hri-login/hri-login.css

Refs: OPS-11508
This has not been tested - I copied the CSS and as much config as I could from the CERF and IASC EntraID PRs, but this needs checking.

feature: add modules and config for EntraID. Untested.

---

.github/workflows/composer-update-config.yml
.github/workflows/composer-update-scripts.yml
.github/workflows/composer-update.yml
composer.json
composer.lock
composer.patches.json

updates: update dev_mode module

---

composer.json
composer.lock

fix: update imageapi_optimize_webp to replace removed function

---

.github/workflows/composer-update.yml

chore: Use the visible / editable maintainers var for PR assignment.

---

html/modules/custom/hr_paragraphs/src/Controller/IcalController.php
html/modules/custom/hr_paragraphs/src/Controller/ParagraphController.php
html/themes/custom/common_design_subtheme/components/hri-calendar/hri-calendar.css
html/themes/custom/common_design_subtheme/components/hri-fullcalendar/hri-fullcalendar.css

fix(bug): Ensure the calendar only adds each event once.

---

html/modules/custom/hr_paragraphs/hr_paragraphs.module
html/modules/custom/hr_paragraphs/src/Controller/RssController.php
html/modules/custom/hr_paragraphs/src/Helpers/HtmlSanitizer.php
html/modules/custom/hr_paragraphs/tests/src/Unit/HtmlSanitizerTest.php
html/themes/custom/common_design_subtheme/templates/paragraph--card-list--featured-highlight.html.twig

feat: Clean up HTML before saving
