UN-OCHA/response-site

config/block.block.common_design_subtheme_breadcrumbs.yml, config/block.block.common_design_subtheme_local_tasks.yml, config/block.block.common_design_subtheme_page_title.yml, config/block.block.tabs.yml, html/themes/custom/common_design_subtheme/common_design_subtheme.info.yml, html/themes/custom/common_design_subtheme/common_design_subtheme.libraries.yml, html/themes/custom/common_design_subtheme/components/cd-tabs/cd-tabs.css
There are two sets of tabs for all users right now. The Editors probably need both sets for the foreseeable future, but anonymous visitors only had Home/View which were both the same URL, and it leads to the page you're already on. Safe to say they don't need those tabs cluttering up the top of their page.
While I was in there, I made the tabs use our HR.info colors.
With PR applied: `drush cim && drush cr`
=> [HRINFO-1129] hide Primary Tabs from visitors

config/block.block.common_design_subtheme_breadcrumbs.yml, config/block.block.common_design_subtheme_local_tasks.yml, config/block.block.common_design_subtheme_page_title.yml, config/block.block.operation_tabs.yml, html/themes/custom/common_design_subtheme/common_design_subtheme.info.yml, html/themes/custom/common_design_subtheme/components/cd-tabs/cd-tabs.css
Builds upon the new labels from yesterday:
=> [HRINFO-1133] emphasize Operation name within secondary tabs

config/core.base_field_override.node.article.promote.yml, config/core.entity_view_display.node.article.operation_tab.yml, config/core.entity_view_mode.node.operation_tab.yml, config/node.type.article.yml, html/modules/custom/hr_paragraphs/src/Breadcrumb/GroupContentBreadcrumbBuilder.php, html/modules/custom/hr_paragraphs/src/Controller/ParagraphController.php, html/modules/custom/hr_paragraphs/templates/group-nodes.html.twig, html/themes/custom/common_design_subtheme/templates/field--paragraph--field-text--text-block.html.twig, html/themes/custom/common_design_subtheme/templates/field--paragraph--field-title--text-block.html.twig, html/themes/custom/common_design_subtheme/templates/node--article--operation-tab.html.twig
It's basically a new View Mode that we can use for template overrides on any content, along with other minor config/twig to hide bylines and titles.
The branch also includes the first fix I could find that restored my ability to view/edit Articles that display at their own URL such as `/node/14` (as opposed to displaying as a tab within an Operation at `/operations/OP/offices`)
=> [HRINFO-1135] visual cleanup of Offices tab

html/modules/custom/hr_paragraphs/templates/hdx-dataset.html.twig, html/themes/custom/common_design_subtheme/templates/hdx-dataset.html.twig, html/themes/custom/common_design_subtheme/templates/layout/rw-river.html.twig
The tables now place `Last updated` as far to the right as possible (sometimes there is a "Files" column which is at the end).
We swapped the words "Managed by" to be "Source" in all tables.
=> Table formatting of various Operation Tabs

html/themes/custom/common_design_subtheme/templates/node--article--operation-tab.html.twig
TIL that contextual links get printed inside the `title_suffix` variable on node templates.
=> [HRINFO-1135] restore contextual links for roles that need them

html/themes/custom/common_design_subtheme/common_design_subtheme.libraries.yml, html/themes/custom/common_design_subtheme/components/hri-text-block/hri-text-block.css, html/themes/custom/common_design_subtheme/templates/field--paragraph--field-text--text-block.html.twig, html/themes/custom/hri_admin/css/admin.css
Fixes problems with floated images:
- Paragraphs that follow weren't clearing automatically.
- Text that flowed next to image had no margin.
- Admin theme tweaks so Editors see the same basic thing as the published content.
=> [HRINFO-1140] Clean up the text blocks

html/modules/custom/hr_paragraphs/src/Controller/ReliefwebController.php
Negating the maps/infographics formats seemed to still provide only maps/infographics. We could probably investigate the `negate` parameter but in the mean time I removed it and provided an explicit allow-list of format IDs.
Refs: HRINFO-1195
=> [HRINFO-1195] explicitly query formats considered to be Reports

html/modules/custom/hr_paragraphs/templates/hr-paragraphs-rss-feed.html.twig, html/themes/custom/common_design_subtheme/templates/hr-paragraphs-rss-feed.html.twig
The template intentionally displays the content with `raw` filter, because it comes from RW with encoded characters such as `&#39;` for apostrophes. However there's no reason to skip `striptags` before the `raw` filter. Easy fix.
=> [HRINFO-1189] strip tags before displaying description

html/themes/custom/common_design_subtheme/components/hri-text-block/hri-text-block.css
The styles originally applied to the Text Block paragraph type only. PR applies the styles to all `field_text` instances, which are used as a universal Description field on most Paragraph types.
=> [HRINFO-1207] apply WYSIWYG clearfix to all instances of field_text

html/modules/custom/hr_paragraphs/templates/hr-paragraphs-rss-feed.html.twig, html/themes/custom/common_design_subtheme/templates/hr-paragraphs-rss-feed.html.twig
Switches the order of operations to avoid outputting broken tags that might result from truncation.
=> [HRINFO-1189] strip tags before truncating RSS description

config/field.storage.paragraph.field_rss_options.yml
Execute the following locally before `drush cim`
```
drush sqlq "delete from paragraph_revision__field_rss_options where field_rss_options_value = \"display_description\""
drush sqlq "delete from paragraph__field_rss_options where field_rss_options_value = \"display_description\""
```
=> Remove obsolete option

html/themes/custom/common_design_subtheme/components/hri-events/hri-events.css, html/themes/custom/common_design_subtheme/components/hri-tooltip/hri-tooltip.css
I built this in FF, which doesn't allow clicking on elements with `opacity: 0`, but curiously Chrome does. When events occur on the same day, the buttons used to appear too close together and clicking the first would cause the second event's tooltip to activate. Not anymore.
=> [HRINFO-1233] eliminate overlap bug in Chrome

html/modules/custom/hr_paragraphs/src/Controller/ReliefwebController.php
Ref: HRINFO-1236
This adds a parameter to the RW thumbnail URLs to prevent browsers from serving stale cached images when the file is replaced upstream.
Check that the parameter is added the thumbnail URLs in the list of RW documents.
=> feat: add cache busting parameter to RW thumbnail URLs

html/modules/custom/hr_paragraphs/component/events/js/fullcalendar.js, html/themes/custom/common_design_subtheme/components/hri-fullcalendar/hri-fullcalendar.css
- Manually adds `tabindex="0"` to each event's markup as it renders to enable keyboard nav.
- Adds an event listener so that when you press <kbd>Enter</kbd> it will open the modal as well.
=> [HRINFO-1240] add keyboard nav to FullCalendar

html/themes/custom/common_design_subtheme/templates/filter-caption.html.twig
Stole the WYSIWYG "floated image with caption" implementation from Seven theme.
=> [HRINFO-1207] copy Seven's template to fix image alignment layout bug

html/themes/custom/common_design_subtheme/components/hri-river/hri-river.css
I can't find the cause of the bug, but in prod we're seeing `cd-typography` defaults applying to RW Rivers, but it doesn't happen on dev/local. I suppose there might be some combo of Paragraphs on the affected page but at any rate, I've added an explicit override.
I also removed the trailing bullet.
=> [RWR-164] River meta layout fix

html/themes/custom/common_design_subtheme/components/hri-river/hri-river.css, html/themes/custom/common_design_subtheme/templates/river-row.html.twig
All Rivers (no matter what datasource) now feature an External Link icon near the title, and a Download icon for the files that can be downloaded.
=> [RWR-142] Add/change some icons

html/themes/custom/common_design_subtheme/common_design_subtheme.libraries.yml, html/themes/custom/common_design_subtheme/components/hri-button/hri-button.css, html/themes/custom/common_design_subtheme/css/brand.css, html/themes/custom/common_design_subtheme/templates/hr-paragraphs-iframe.html.twig
1. OCHA Services "See All" button now matches RW branding and has contrast of 9:1
2. iframes now output "Embedded media" as title in all cases. If we wanted to customize I'd add a new field to the paragraph but in the mean time at least it announces something
3. We do intentionally have `alt=""` on our River results when a preview image is available. As noted in the ticket this does seem to be best practice but I assume the tool can't divine that with certainty and has to call it out.
@left23 I tagged you since you're familiar with test results and my normal approver is 🌴  — no need to load it up locally, we can look on dev or have Check1st do another audit after deploying.
=> [RWR-177] Address Check1st audit results

config/image.style.highlight_thumb.yml, html/themes/custom/common_design_subtheme/components/hri-card-list/hri-card-list.css, html/themes/custom/common_design_subtheme/components/hri-heading/hri-heading.css
The homepage had two paragraph types with mobile bugs:
- Heading with Link had overlapping text. That's impossible now because it's a flexbox that wraps when space doesn't permit.
- Card List was 2-col within all viewport sizes. It's now 1-col until space permits, and I cleaned it up a little to permit easier customization in other situations. Updated the "Heading Thumbnail" image size to match our CSS breakpoint.
=> [multi-ticket] Mobile fixes

html/modules/custom/hr_paragraphs/src/Controller/HdxController.php
Label change for HDX filters. I left the machine key as `groups`.
=> [RWR-166] label change for HDX filters

config/core.entity_view_display.paragraph.reliefweb_document.preview.yml, html/modules/custom/hr_paragraphs/templates/hr-paragraphs-rw-list.html.twig
Display `field_title`/`field_text` in editor previews of RW Document para type.
=> [RWR-186] display RW document title/text fields in Editor previews

config/views.view.audit_paragraphs.yml
Views display which lives at `/admin/reports/contains-layout` so that **Global Editor** or **Administrator** roles can see a list of Nodes that contain at least one Layout paragraph inside `field_paragraphs`:
=> [RWR-176] administrative report to find nodes containing Layout paras

html/themes/custom/hri_admin/css/admin.css
In the comments Marina asked if the RW URL could be nudged away from the title.
Refs: RWR-181
=> fix: title margins for Editor previews

html/themes/custom/common_design_subtheme/common_design_subtheme.theme
Firefox was dealing with our markup just fine. Chrome needed some attention. The observable side-effect is the dark-mode favicon. It's black on grey before checking the PR out, then (after a cache-clear) it will be white on grey:
=> [RWR-193] Chrome can recognize SVG favicon now

config/core.entity_form_display.paragraph.reliefweb_key_figures.default.yml, config/core.entity_view_display.paragraph.reliefweb_key_figures.default.yml, config/field.field.group.cluster.field_paragraphs.yml, config/field.field.group.operation.field_paragraphs.yml, config/field.field.node.landing_page.field_paragraphs.yml, config/field.field.node.landing_page.field_paragraphs_secondary.yml, config/field.field.node.page.field_paragraphs.yml, config/field.field.paragraph.reliefweb_key_figures.field_country.yml, config/field.field.paragraph.reliefweb_key_figures.field_max_number_of_items.yml, config/field.field.paragraph.reliefweb_key_figures.field_text.yml, config/field.field.paragraph.reliefweb_key_figures.field_title.yml, config/field.storage.paragraph.field_country.yml, config/field.storage.paragraph.field_iframe_url.yml, config/paragraphs.paragraphs_type.reliefweb_key_figures.yml, html/modules/custom/hr_paragraphs/hr_paragraphs.module, html/modules/custom/hr_paragraphs/hr_paragraphs.services.yml, html/modules/custom/hr_paragraphs/src/Controller/KeyFiguresController.php, html/modules/custom/hr_paragraphs/templates/hr-paragraphs-rw-key-figures.html.twig, html/themes/custom/common_design_subtheme/common_design_subtheme.libraries.yml, html/themes/custom/common_design_subtheme/components/rw-key-figures/rw-key-figures.css, html/themes/custom/common_design_subtheme/templates/hr-paragraphs-rw-key-figures.html.twig
Place the Paragraph and pick a country from the list (and optionally a max number of items). It should render more or less like ReliefWeb. Notable differences:
- Commas are missing from Key Figure number
- Sparklines are missing. I saw how they can be constructed but omitted it to build this MVP in one day.
- "No change since" dates also omitted. The data exists in the source, just needs to be added to `buildKeyFigures()`
=> [RWR-196] API-driven Key Figures paragraph

html/modules/custom/hr_paragraphs/hr_paragraphs.module, html/modules/custom/hr_paragraphs/src/Controller/KeyFiguresController.php, html/modules/custom/hr_paragraphs/templates/hr-paragraphs-rw-key-figures.html.twig, html/themes/custom/common_design_subtheme/components/hri-global-styling/hri-global-styling.css, html/themes/custom/common_design_subtheme/templates/hr-paragraphs-rw-key-figures.html.twig, html/themes/custom/hri_admin/css/admin.css
- Add the “No change since” and last-updated date to each Key Figure
- Display the sparklines
- Add a link to RW crisis figures section of the relevant country page
=> [RWR-220] improve display of Key Figures

html/modules/custom/hr_paragraphs/templates/hr-paragraphs-rss-feed.html.twig, html/themes/custom/common_design_subtheme/templates/hr-paragraphs-rss-feed.html.twig
Remove all the security precautions from external links when we detect that reliefweb.int is the destination. The default is still to add them to any external link.
=> [RWR-225] don't be so paranoid with reliefweb.int external links

config/core.entity_form_display.paragraph.featured_highlight.default.yml, config/field.field.paragraph.featured_highlight.field_image.yml, config/field.field.paragraph.featured_highlight.field_text.yml, html/themes/custom/common_design_subtheme/templates/paragraph--featured-highlight.html.twig, html/themes/custom/hri_admin/css/admin.css, html/themes/custom/hri_admin/hri_admin.libraries.yml, html/themes/custom/hri_admin/templates/text-format-wrapper.html.twig
=> [RWR-219] add Help text to Featured Highlights

html/themes/custom/common_design_subtheme/components/hri-card-list/hri-card-list.css, html/themes/custom/common_design_subtheme/components/hri-card/hri-card.css
before/after are in ticket, but the images no longer cover the title/text fields when the image is missing.
=> [RWR-228] fix broken images on Card List

html/themes/custom/common_design_subtheme/components/hri-card-list/hri-card-list.css
- dangling Cards no longer expand to full-width
- logic for `flex-basis` is more accurate
Refs: RWR-248
=> [RWR-248] Card List layout fixes

config/views.view.locations.yml
Using lang switcher in global header allows a visitor to flip between sets of operations in the available languages.
=> [RWR-253] Locations page should only show entries for current UI language

config/core.entity_form_display.paragraph.search_results.default.yml, config/core.entity_view_display.paragraph.search_results.default.yml, config/field.field.paragraph.search_results.field_gcse_id.yml, config/field.storage.paragraph.field_gcse_id.yml, config/paragraphs.paragraphs_type.search_results.yml, html/themes/custom/common_design_subtheme/components/google-cse/google-cse.css, html/themes/custom/common_design_subtheme/templates/cd/cd-header/cd-search.html.twig, html/themes/custom/common_design_subtheme/templates/page.html.twig, html/themes/custom/common_design_subtheme/templates/paragraph--search-results.html.twig
Refs: RWR-257
- Check out branch and import config
- Create a new Node (I used Page type) and add the Search Results paragraph type with ID (see RWR-257)
- Set the Node's URL alias to `/search` if it isn't already
- Visit the homepage and do a search from the Global search in the header.
- The Search in the global header should look like the CD Search usually does
- The Search results page Search input (GCSE) should have brand colours for the search button
=> RWR-257 Two page layout for GCSE

html/themes/custom/common_design_subtheme/common_design_subtheme.libraries.yml, html/themes/custom/common_design_subtheme/components/hri-iframe/hri-iframe.css, html/themes/custom/common_design_subtheme/components/hri-iframe/hri-iframe.js, html/themes/custom/common_design_subtheme/templates/hr-paragraphs-iframe.html.twig
It wasn't possible to have a pure CSS solution, since `attr()` is only guaranteed to work within values for the `content` property, [not other properties](https://developer.mozilla.org/en-US/docs/Web/CSS/attr).
Refs: RWR-275
=> [RWR-275] hri-iframe auto aspect-ratio now driven by JS

html/themes/custom/common_design_subtheme/components/hri-layout/hri-layout.css, html/themes/custom/common_design_subtheme/components/hri-rss-feed/hri-rss-feed.css, html/themes/custom/common_design_subtheme/components/hri-text-block/hri-text-block.css, html/themes/custom/common_design_subtheme/css/styles.css
Follow up to https://github.com/UN-OCHA/response-site/pull/420
chore: remove commented out rules for final tidy
Refs: RWR-260
=> RWR-260 Final tidy, remove commented out CSS rules

html/modules/custom/hr_paragraphs/hr_paragraphs.module
Refs: RW-283
This simply removes the query parameters from the URL used in reliefweb document paragraphs to ensure the URL alias lookup works.
**Before checking out this branch**
1. Edit a page (ex: `/fiji`)
2. Add a `reliefweb document` paragraph with a URL to a RW document with a query parameter, ex: `https://reliefweb.int/report/mali/mali-note-dinformations-humanitaires-sur-la-region-de-kidal-rapport-de-situation-1-18-novembre-2022?test`
3. Save the paragraph
4. Check that the document is not displayed in the paragraph preview
**After checking out this branch**
Repeat the above, (4) should show the document in the paragraph preview.
=> [RW-283] Remove query parameters of URL used in reliefweb document paragraphs

html/themes/custom/common_design_subtheme/templates/views-view--locations--page-locations.html.twig, html/themes/custom/common_design_subtheme/templates/views-view-grid.html.twig
Refs: RWR-324
Specifically for oPt since it was creating a lowercase `o` in the heading and letter-navigation.
=> fix(locations): always capitalize letter-based navigation

docker/Dockerfile
The builder is no longer maintained, since the current common_design theme no longer requires sass to build assets.
Refs: OPS-9161
=> chore: Use the normal PHP image for the build.

PATCHES/linkchecker-previous-revisions-3366753.patch, composer.patches.json, html/modules/custom/hr_paragraphs/hr_paragraphs.module, html/modules/custom/hr_paragraphs/src/Plugin/views/filter/LinkcheckerLinkActiveRevisions.php
Refs: RWR-355
This is only a part of the solution for the Dead links view, but I think it gets us a little closer.
This patch alters the field where the link is found if it's in a previous version of a paragraph.
("OCHA_Mali" is a good url to test with, as there is currently one version in a current paragraph and one in a previous revision.) 
@attiks if I understand right, the next step is to add a views filter plugin for the Entity Label field. Is that right?
=> fix: include patch to recognize previous revisions

config/views.view.db_links.yml
RWR-355 - follow up to previous deploy - include the configuration so the filter is added to the view. (Has been altered via config on production, this to keep the config up-to-date.)
=> chore: include views config for db_links filter

config/field.field.paragraph.featured_highlight.field_text.yml, config/social_auth_hid.settings.yml
Makes the text optional on cards. The layout will survive:
=> [RWR-373] Make text optional on cards

html/modules/custom/hr_paragraphs/hr_paragraphs.module, html/modules/custom/hr_paragraphs/src/Controller/ReliefwebController.php
Refs: RWR-368
This fixes the query to the RW API when there RW river URL contains a date filter.
Examples:
1. https://reliefweb.int/updates?view=reports&advanced-search=%28DA20230801-%29 -- (`from` date only)
2. https://reliefweb.int/updates?view=reports&advanced-search=%28DA20230924%29 -- (`from` and `to` dates, same date = on the day)
3. https://reliefweb.int/updates?view=reports&advanced-search=%28DA20230801-%29 -- (`from` and `to` dates)
1. Before checking out this branch, add 3 RW feeds paragraph types to a page with the URLs above
4. Save and confirm you get the "ReliefWeb data is currently not available." message for the 3 paragraphs.
5. Check out the branch, clear the cache
6. Refresh the page from (2) and confirm that the RW reports appear in each paragraph and match what is …
=> [RWR-368] Proper processing of date filters for the RW rivers

config/views.view.db_links.yml, html/modules/custom/hr_paragraphs/hr_paragraphs.module, html/modules/custom/hr_paragraphs/src/Plugin/views/field/LinkcheckerLinkGroupEntityLabel.php
=> feature: Link to operation

config/environment_indicator.indicator.yml, config/user.role.authenticated.yml, config/user.role.global_editor.yml, config/views.view.db_links.yml, html/modules/custom/hr_paragraphs/hr_paragraphs.module, html/modules/custom/hr_paragraphs/src/Plugin/views/field/LinkcheckerLinkGroupEntityLink.php, html/modules/custom/hr_paragraphs/src/Plugin/views/field/LinkcheckerLinkPageEntityLink.php
=> feat: Add env indicator for production

composer.json, composer.lock
Refs: RWR-354
The ticket says "Module to remain disabled until further notice. Content Squad will review users manually on a regular basis for now." but no sign of it being used again soon and if so we can add it again. This PR removes the module completely to keep things more tidy.
=> chore: remove unused user_expire module

composer.json
Refs: OPS-9635
Composer sometimes prompts to allow or deny the preserve-paths plugin, even though it was removed some time ago. Not sure why it happens, but hoping it won't happen again.
=> chore: remove outdated allow-plugin directive

docker/Dockerfile
Refs: OPS-9635
Composer is already updated in composer.lock so tomorrow's deployment should fix the issue for the moment anyway:
=> chore: include composer self-update step

html/themes/custom/common_design_subtheme/templates/paragraph--card-list--featured-highlight.html.twig
There might be a better way
Refs: #RWR-404
=> bug: Avoid nbsp

composer.lock, composer.patches.json
Refs: OPS-10181
Tried updating dynamic_entity_reference module so we could remove a patch to use an earlier version https://www.drupal.org/project/linkchecker/issues/3346793 - but turns out it had already been updated so the patch wasn't needed.
I also made whitespace consistent in the patch https://github.com/UN-OCHA/response-site/compare/OPS-10181-avoid-alterable-patches?expand=1&w=1 shows the actual change.
=> chore: update linkchecker dependency to remove a patch

html/modules/custom/hr_paragraphs/hr_paragraphs.info.yml
Because otherwise, you get bad errors when you try to uninstall them.
Refs: OPS-10529
=> fix: Ensure that hr_paragraphs depends on the module whose classes it uses.

docker/services.yml
I'm not sure if the `destination` parameter is treated special and others not; as far as I know only `destination` has the potential of making a user go somewhere else, the rest would (at worst) generate an error because an invalid parm could get passed to a function (pager, filter, whatevs) so this change *may* not be strictly needed.
It would seem like rather large oversight if this got built into Drupal and enabled by default if it was an actual security issue.
See https://www.drupal.org/docs/drupal-apis/cache-api/cache-contexts
Refs: OPS-10407
=> security: Vary cache context by query_args, to avoid potential cache poisining

composer.json, composer.lock
Refs: OPS-10638
From the README of layout_paragraphs:
```
- Ensure asset packagist has been set up for your project.
- Run `composer require bower-asset/dragula drupal/paragraphs drupal/layout_paragraphs`
- Install Layout Paragraphs.
```
We've been using version 2 for months now, so not sure if this will fix the issue raised in testing: https://docs.google.com/document/d/1IwEmGp47aZXy5NHC8QYTSPmm_9tch7ZuOJXKYU62hSY/edit?pli=1#heading=h.hzhhenbl1wo3
=> chore: include missing package

PATCHES/imagemagick-ints.patch, composer.patches.json
Refs: RWR-456
This should probably be fixed in the translation stage, but this removes the error for now.
=> fix: patch for imagemagick translated dimensions

html/modules/custom/rwr_sitrep/rwr_sitrep.module
=> fix: use correct dsr label for operations

html/modules/custom/rwr_sitrep/rwr_sitrep.module, html/themes/custom/common_design_subtheme/templates/node--page--full--pdf.html.twig
Refs: RWR-495
This fix makes me think I should be passing the language along in a better way, but this avoids snap failing when content language is 'undefined' or 'not applicable'. (And assumes undefined languages are all 'ltr').
=> fix: handle snaps with undefined language
